### ISSUE TITLE
Training Codes

### ISSUE THREAD

**Issue by eslambakr** [rohjunha/language-refer#1]
Dears,

Congrats on your amazing work!
And thanks for sharing the source code,
I am just wondering are you planning to release the training codes?

Thanks in advance.

**Comment by rohjunha** [comment]
Hi @eslambakr, sorry for the late response. We are preparing to release the training code but it will take some time. Once we release the code, we will let you know. Thank you for your interest!

**Comment by rohjunha** [comment]
Hi @eslambakr, the training code has been released and I am closing the issue.
