### ISSUE TITLE
Train on Nr3D with Corrected Orientations

### ISSUE THREAD

**Issue by ZiyuGuo99** [rohjunha/language-refer#3]
Thanks for your excellent work!
How could I train on Nr3D dataset with corrected orientations? I haven't found any related code for processing the data or available annotated dataset on your project page. 
Looking forward to your reply and I'm sorry if it was my mistake. : )

**Comment by rohjunha** [comment]
Hi @SarahGuo1999, thank you for your interest in our work. I am taking a vacation and unable to update the code right now. I will try to provide the raw annotation data or the training option in the code in a few weeks.

**Comment by ZiyuGuo99** [comment]
Sorry for the late reply. 
Thanks! I will wait for your update. Have a nice vacation!
