### ISSUE TITLE
Can not reproduce the results

### ISSUE THREAD

**Issue by eslambakr** [rohjunha/language-refer#5]
Dears,

Thanks for sharing your codes. It was really easy to run your training code without any efforts.
However, unfortunately, I couldn't reproduce your results.
For Nr3D, I am using your code without any changes and your configuration, e.g. training for 300 epoch, however, I couldn't get the same results mentioned in the paper (43.9%) where I got only 34%.
This 10% drop is too weird, am I doing some thing wrong? I exactly followed the readme and didn't change anything in your configuration.

For Sr, it is still running but after 160 epoch I have got only 42% however, in the paper it should be 56%.

Therefore, if there is anyone try to reproduce the results, your advice will be much appreciated.
Thanks in advance!

**Comment by rohjunha** [comment]
Hi @eslambakr, thank you for your interest.
The public code here is simplified one from the private repo so the result can be different from that from the private repo.
I am sorry that I could not specify the reason and the repo is not well-prepared at the time of publication; now this repo is not actively managed and hard to track down the original training code as the private repo is messy.
If you still want to investigate further to reproduce the result, please drop me an email.
